# Generated by Django 2.2.7 on 2020-11-13 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siwieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logbook',
            name='user',
            field=models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
