# Generated by Django 2.2.7 on 2020-11-13 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siwieapp', '0002_logbook_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logbook',
            name='user',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
