# Generated by Django 2.2.7 on 2020-11-16 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siwieapp', '0003_auto_20201113_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='media/he.png', null=True, upload_to='user/'),
        ),
    ]
