# Generated by Django 2.2.7 on 2020-11-16 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siwieapp', '0004_profile_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_image',
        ),
    ]
