# Generated by Django 3.1.3 on 2020-11-25 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siwieapp', '0006_profile_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logbook',
            old_name='user',
            new_name='owner',
        ),
    ]
